required = [
  "github.com/heptio/authenticator/cmd/heptio-authenticator-aws",
  "github.com/vektra/mockery/cmd/mockery",
]

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.14.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/kubicorn/kubicorn"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[override]]
  branch = "release-1.10"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.10"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/kops"
  version = "1.9.1"

[[override]]
  name = "github.com/heptio/authenticator"
  source = "github.com/heptio/aws-iam-authenticator"
  revision = "d9bfef19b2b89518465d4fd0bc9a75bd4a8b715e"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v7.0.0"

#[[constraint]]
#  name = "k8s.io/kubernetes"
#  version = "1.10.3"

[[constraint]]
  branch = "master"
  name = "github.com/weaveworks/launcher"

[[constraint]]
  branch = "master"
  name = "github.com/kballard/go-shellquote"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  branch = "master"
  name = "github.com/vektra/mockery"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.5.0"

[[override]]
  name = "github.com/gophercloud/gophercloud"
  revision = "8183543f90d1aef267a5ecc209f2e0715b355acb"

[[constraint]]
  branch = "master"
  name = "github.com/dlespiau/kube-test-harness"
