apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: vpc-admission-webhook-cfg
  labels:
    app: vpc-admission-webhook
webhooks:
  - name: vpc-admission-webhook.amazonaws.com
    clientConfig:
      service:
        name: vpc-admission-webhook-svc
        namespace: kube-system
        path: "/mutate"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
