name: Publish Release type
on:
  workflow_call:
    inputs:
      isReleaseCandidate:
        required: true
        type: boolean
      name:
        required: true
        type: string
    secrets:
      githubToken:
        required: true
      slackToken:
        required: true

jobs:
  publish-release:
    name: ${{ inputs.isReleaseCandidate && 'prerelease' || 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        run: |
          echo "Available storage:"
          df -h && echo
          sudo docker image prune --all --force
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          echo "Available storage:"
          df -h
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - name: Setup build environment
        uses: ./.github/actions/setup-build
      - name: Publish release
        if: ${{ !inputs.isReleaseCandidate }}
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
        run: |
          ./build/scripts/do-release.sh
      - name: Publish release candidate
        if: ${{ inputs.isReleaseCandidate }}
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
        run: |
          ./build/scripts/do-release-candidate.sh
      - name: get version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
